inherit_from: .rubocop_todo.yml

# Offense count: 3
Lint/AmbiguousOperator:
  Enabled: true

# Offense count: 11
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# Offense count: 14
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

# Offense count: 1
# Configuration parameters: AlignWith, SupportedStyles.
Lint/DefEndAlignment:
  Enabled: true

# Offense count: 16
# Cop supports --auto-correct.
Lint/DeprecatedClassMethods:
  Enabled: true

# Offense count: 3
Lint/Eval:
  Enabled: false

# Offense count: 1
Lint/HandleExceptions:
  Enabled: true

# Offense count: 13
# Cop supports --auto-correct.
Lint/RescueException:
  Enabled: false

# Offense count: 8
Lint/ShadowingOuterLocalVariable:
  Enabled: true

# Offense count: 9
# Cop supports --auto-correct.
Lint/StringConversionInInterpolation:
  Enabled: true

# Offense count: 9
# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

# Offense count: 18
# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: false

# Offense count: 1
Lint/UselessAccessModifier:
  Enabled: true

# Offense count: 22
Lint/UselessAssignment:
  Enabled: true

# Offense count: 1
Style/AccessorMethodName:
  Enabled: true

# Offense count: 2
# Cop supports --auto-correct.
Style/AlignArray:
  Enabled: true

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
Style/AlignHash:
  Enabled: true

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AlignParameters:
  Enabled: true

# Offense count: 58
# Cop supports --auto-correct.
Style/AndOr:
  Enabled: true

# Offense count: 5
Style/BlockNesting:
  Max: 4

# Offense count: 3
# Cop supports --auto-correct.
Style/Blocks:
  Enabled: true

# Offense count: 40
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BracesAroundHashParameters:
  Enabled: truetf


