#!/bin/bash
# :vim:sw=2:ts=2:et:
#
# This file is installed in /usr/share/foreman/script/foreman-debug.d where
# it is picked by foreman-debug reporting tool
#

# proxy-related configs and logs
add_files /etc/foreman{-proxy,-proxy/settings.d}/* /var/log/foreman{-proxy,-installer}/*.log*
add_files /etc/{sysconfig,default}/foreman-proxy

# ISC dhcp
add_files /etc/sysconfig/named /etc/default/bind
add_files /etc/{sysconfig,default}/dhcp*
add_files /etc/dhcp/*.conf /var/lib/dhcp/*.leases

# ISC tftp
add_files /etc/xinetd.d/tftp
[ -d "/tftpboot" ] && add_cmd "find /tftpboot -exec ls -ld {} +" "tftpboot_tree"
[ -d "/srv/tftp" ] && add_cmd "find /srv/tftp -exec ls -ld {} +" "tftpboot_tree"
[ -d "/var/lib/tftpboot" ] && add_cmd "find /var/lib/tftpboot -exec ls -ld {} +" "tftpboot_tree"

# ISC bind
add_files /etc/named.conf /var/log/named.log
add_files /var/named/* /var/named/{data,dynamic,slaves}/*

# Puppet master and CA
add_files /var/lib/puppet/ssl/certs/$(hostname -f).pem /var/lib/puppet/ssl/certs/ca.pem
add_files /etc/puppet/*.conf /etc/puppet/rack/* /etc/puppet/manifests/* /var/log/puppet/*.log*
add_files /etc/puppet/ssl/ca/inventory.txt /var/lib/puppet/ssl/ca/inventory.txt
add_cmd "find /etc/puppet/modules -exec ls -ld {} +" "puppet_manifests_tree"
add_files /etc/{httpd,apache2}/conf/*
add_files /etc/{httpd,apache2}/conf.d/*
add_files /var/log/puppet
add_files /var/log/{httpd,apache2}/*error_log*
