#!/bin/bash
# :vim:sw=2:ts=2:et:
#
# This file is installed in /usr/share/foreman/script/foreman-debug.d where
# it is picked by foreman-debug reporting tool
#

# proxy-related configs and logs
add_files /etc/foreman{-proxy,-proxy/settings.d}/*.{yml,yaml,conf}
add_files /etc/{sysconfig,default}/foreman-proxy
add_files /var/log/foreman-proxy/cron*.log*
add_files /var/log/foreman-proxy/migrate_settings*.log*
add_files /var/log/foreman-proxy/proxy*.log*
add_files /var/log/foreman-proxy/smart_proxy_dynflow_core*.log*

# ISC dhcp
add_files /etc/sysconfig/named /etc/default/bind
add_files /etc/{sysconfig,default}/dhcp*
add_files /etc/dhcp/*.conf /var/lib/dhcp/*.leases

# ISC tftp
add_files /etc/xinetd.d/tftp
[ -d "/tftpboot" ] && add_cmd "find /tftpboot -exec ls -ld {} +" "tftpboot_tree"
[ -d "/srv/tftp" ] && add_cmd "find /srv/tftp -exec ls -ld {} +" "tftpboot_tree"
[ -d "/var/lib/tftpboot" ] && add_cmd "find /var/lib/tftpboot -exec ls -ld {} +" "tftpboot_tree"

# ISC bind
add_files /etc/named.conf
add_files /var/log/named*.log
add_files /var/named

# Puppet master and CA
add_files /var/lib/puppet/ssl/certs/$(hostname -f).pem /var/lib/puppet/ssl/certs/ca.pem
add_files /etc/puppet/*.conf /etc/puppet/rack/* /etc/puppet/manifests/*
add_files /var/log/puppet/*.log*
add_files /etc/puppet/ssl/ca/inventory.txt /var/lib/puppet/ssl/ca/inventory.txt
add_cmd "find /etc/puppet/modules -exec ls -ld {} +" "puppet_manifests_tree"

# Puppet 4
add_files /etc/puppetlabs/puppet/ssl/certs/$(hostname -f).pem /etc/puppetlabs/puppet/ssl/certs/ca.pem
add_files /etc/puppetlabs/puppet/*.conf /etc/puppetlabs/puppetserver/conf.d/*.conf /etc/puppetlabs/puppet/rack/* /etc/puppetlabs/puppet/manifests/*
add_files /var/log/puppetlabs/puppetserver/*.log*
add_files /etc/puppetlabs/puppet/ssl/ca/inventory.txt /var/lib/puppetlabs/puppet/ssl/ca/inventory.txt
add_cmd "find /etc/puppetlabs/code/modules -exec ls -ld {} +" "puppet_manifests_tree"

add_files /etc/{httpd,apache2}/conf/*
add_files /etc/{httpd,apache2}/conf.d/*
add_files /var/log/{httpd,apache2}/*error_log*
