#! /bin/sh
# a simple script to create a Smart Proxy Official relase.

cd /tmp
rm -rf foreman-proxy
git clone git://github.com/theforeman/smart-proxy.git foreman-proxy
cd foreman-proxy

rm -rf `find -name ".git*"`
cd /tmp

tar cv foreman-proxy | bzip2 -9 > /tmp/foreman-proxy-$1.tar.bz2
rm -rf foreman-proxy

echo "Don't forget to tag the release"
